<a href="https://colab.research.google.com/github/nikpaw/my_first_repo/blob/main/Data_Foreign_Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import matplotlib.pylab as plt
import numpy as np

# Foreign Population in Germany by state

In [3]:
# Upload the "12521-0021_flat.csv" file into the notebook and set it as a dataframe
from google.colab import files
uploaded = files.upload()

Saving 12521-0021_flat.csv to 12521-0021_flat.csv

In [4]:
import io
foreign_data = pd.read_csv(io.BytesIO(uploaded['12521-0021_flat.csv']), encoding="windows_1258")

foreign_data.info()

foreign_data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 432 entries, 0 to 431
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Statistik_Code              432 non-null    int64
 1   Statistik_Label             432 non-null    object
 2   Zeit_Code                   432 non-null    object
 3   Zeit_Label                  432 non-null    object
 4   Zeit                        432 non-null    object
 5   1_Merkmal_Code              432 non-null    object
 6   1_Merkmal_Label             432 non-null    object
 7   1_Auspraegung_Code          432 non-null    int64
 8   1_Auspraegung_Label         432 non-null    object
 9   2_Merkmal_Code              432 non-null    object
 10  2_Merkmal_Label             432 non-null    object
 11  2_Auspraegung_Code          288 non-null    object
 12  2_Auspraegung_Label         432 non-null    object
 13  3_Merkmal_Code              432 non-null    object
 14  3_Merkmal_Label             432 non-null    object
 15  3_Auspraegung_Code          384 non-null    object
 16  3_Auspraegung_Label         432 non-null    object
 17  BEV027__Auslaender__Anzahl  432 non-null    int64
dtypes: int64(3), object(15)
memory usage: 60.9+ KB

,Statistik_Code,Statistik_Label,Zeit_Code,Zeit_Label,Zeit,1_Merkmal_Code,1_Merkmal_Label,1_Auspraegung_Code,1_Auspraegung_Label,2_Merkmal_Code,2_Merkmal_Label,2_Auspraegung_Code,2_Auspraegung_Label,3_Merkmal_Code,3_Merkmal_Label,3_Auspraegung_Code,3_Auspraegung_Label,BEV027__Auslaender__Anzahl
0,12521,Ausländerstatistik,STAG,Stichtag,31.12.2021,DLAND,Bundesländer,8,Baden-Württemberg,GES,Geschlecht,GESM,männlich,STAAG6,Staatsangehörigkeit,NaN,Insgesamt,998975
1,12521,Ausländerstatistik,STAG,Stichtag,31.12.2021,DLAND,Bundesländer,8,Baden-Württemberg,GES,Geschlecht,GESM,männlich,STAAG6,Staatsangehörigkeit,ST124,Belgien,1295
2,12521,Ausländerstatistik,STAG,Stichtag,31.12.2021,DLAND,Bundesländer,8,Baden-Württemberg,GES,Geschlecht,GESM,männlich,STAAG6,Staatsangehörigkeit,ST126,Dänemark,605
3,12521,Ausländerstatistik,STAG,Stichtag,31.12.2021,DLAND,Bundesländer,8,Baden-Württemberg,GES,Geschlecht,GESM,männlich,STAAG6,Staatsangehörigkeit,ST129,Frankreich,15220
4,12521,Ausländerstatistik,STAG,Stichtag,31.12.2021,DLAND,Bundesländer,8,Baden-Württemberg,GES,Geschlecht,GESM,männlich,STAAG6,Staatsangehörigkeit,ST148,Niederlande,4350
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,12521,Ausländerstatistik,STAG,Stichtag,31.12.2021,DLAND,Bundesländer,16,Thüringen,GES,Geschlecht,NaN,Insgesamt,STAAG6,Staatsangehörigkeit,ST148,Niederlande,605
428,12521,Ausländerstatistik,STAG,Stichtag,31.12.2021,DLAND,Bundesländer,16,Thüringen,GES,Geschlecht,NaN,Insgesamt,STAAG6,Staatsangehörigkeit,ST151,Österreich,785
429,12521,Ausländerstatistik,STAG,Stichtag,31.12.2021,DLAND,Bundesländer,16,Thüringen,GES,Geschlecht,NaN,Insgesamt,STAAG6,Staatsangehörigkeit,ST152,Polen,13210
430,12521,Ausländerstatistik,STAG,Stichtag,31.12.2021,DLAND,Bundesländer,16,Thüringen,GES,Geschlecht,NaN,Insgesamt,STAAG6,Staatsangehörigkeit,ST158,Schweiz,275
431,12521,Ausländerstatistik,STAG,Stichtag,31.12.2021,DLAND,Bundesländer,16,Thüringen,GES,Geschlecht,NaN,Insgesamt,STAAG6,Staatsangehörigkeit,ST164,Tschechien,1715

In [17]:
# rename columns, cleaning data
  # renaming: "Statistik_Code"	"Statistik_Label"	"Zeit_Code"	"Zeit_Label"	"Zeit" are all the same for this table. They can be added as header/general info about the table, no need to keep them inside the table
  # renaming: 1_Auspraegung_Label = State of residence (in Germany); 2_Auspraegung_Label = Sex; 3_Auspraegung_Label = Citizenship (outside Germany); BEV027__Auslaender__Anzahl = Number of Foreigners in the state
foreign_data_renamed = foreign_data.rename(columns={"1_Auspraegung_Label": "State of residence (in Germany)", "2_Auspraegung_Label": "Sex", "3_Auspraegung_Label": "Citizenship (outside Germany)", "BEV027__Auslaender__Anzahl": "Number of Foreigners in the state"})
# filter data for rows and columns that matter in the given context
  # suggest filter: from here on, using only "insgesamt" for Sex, not distinguishing male/female
foreign_data_renamed_filtered = foreign_data_renamed.loc[foreign_data_renamed["Sex"] == "Insgesamt"]
  # filter for the renamed variables (excluding sex, as it is the same across all observations after the last step) 
foreign_data_renamed_filtered = foreign_data_renamed_filtered.filter(items=["State of residence (in Germany)", "Citizenship (outside Germany)", "Number of Foreigners in the state"])

# make observation unit "state of residence", widen "Citizenship"
foreign_data_renamed_filtered = pd.pivot(foreign_data_renamed_filtered, index = "State of residence (in Germany)", columns = "Citizenship (outside Germany)", values = "Number of Foreigners in the state")

# order columns by country_name, "insgesamt" as a final column 
foreign_data_renamed_filtered = foreign_data_renamed_filtered [["Belgien", "Dänemark", "Frankreich", "Niederlande", "Österreich", "Polen", "Schweiz", "Tschechien", "Insgesamt"]]

foreign_data_renamed_filtered

Citizenship (outside Germany),Belgien,Dänemark,Frankreich,Niederlande,Österreich,Polen,Schweiz,Tschechien,Insgesamt
State of residence (in Germany),,,,,,,,,
Baden-Württemberg,2520,1245,29540,7915,26405,83870,13510,6765,1885925
Bayern,2950,2130,23100,9855,85365,117825,7095,26395,2051505
Berlin,2540,3475,22600,7885,14025,66855,3425,2885,848400
Brandenburg,215,180,1005,1145,1405,25510,560,785,149540
Bremen,200,215,1035,1025,815,9460,265,215,140330
Hamburg,570,1530,4465,2525,3875,23310,1350,645,328375
Hessen,2635,1105,13285,8060,13280,80695,3050,4180,1163800
Mecklenburg-Vorpommern,85,170,415,840,700,15720,365,430,87410
Niedersachsen,1390,1455,4875,29745,6795,100220,2435,2225,895490
Nordrhein-Westfalen,12815,2145,20575,69315,21310,220530,5335,5340,2815800
Rheinland-Pfalz,2610,495,8265,6730,5210,44360,1540,1835,532230
Saarland,430,85,6790,640,1015,5780,315,290,134350
Sachsen,360,170,1830,1105,1915,22040,795,8155,244415
Sachsen-Anhalt,140,65,425,795,670,12225,265,855,127670
Schleswig-Holstein,440,7020,1780,2245,3120,29395,1110,565,286270
Thüringen,130,60,510,605,785,13210,275,1715,126270

# Population with Migrant Background in Germany

In [16]:
# Upload the "Data_Migrant_Background_Small_Comma_adapted.txt" file into the notebook and set it as a dataframe
from google.colab import files
uploaded = files.upload()

Saving Data_Migrant_Background_Small_Comma_adapted.txt to Data_Migrant_Background_Small_Comma_adapted (3).txt

In [19]:
import io
# "5 Bevölkerung 2020 nach Migrationsstatus, Ländern und Geschlecht"
# numbers in 1 000
migrant_data = pd.read_csv(io.BytesIO(uploaded['Data_Migrant_Background_Small_Comma_adapted.txt']), encoding="windows_1258")

migrant_data = migrant_data.T

migrant_data

,0,1,2,3,4,5,6,7,8,9,...,29,30,31,32,33,34,35,36,37,38
ï»¿Detaillierter Migrationsstatus,NaN,BevĂ¶lkerung in Privathaushalten insgesamt,Personen ohne Migrationshintergrund,Personen mit Migrationshintergrund im weiteren...,Personen mit Migrationshintergrund,Europa,â€“ EU-27,Bulgarien,Frankreich,Griechenland,...,Vereinigtes KĂ¶nigreich,Unbestimmt,Ohne Angabe,nachrichtlich:,â€“ Gebiet des ehemaligen Jugoslawien,â€“ Gebiet der ehemaligen Sowjetunion,â€“ Gastarbeiteranwerbestaaten,â€“ vor 2004 beigetretene EU-Staaten,â€“ seit 2004 beigetretene EU-Staaten,NaN
Deutschland,NaN,81 861,59 976,21 885,21 885,13 798,7 475,273,247,467,...,176,694,1 030,NaN,1 956,3 301,6 906,2 965,4 511,NaN
FrĂ¼heres Bundesgebiet und Berlin,NaN,69 577,48 804,20 773,20 773,13 218,7 100,245,240,454,...,170,677,950,NaN,1 922,3 079,6 798,2 894,4 206,NaN
Neue LĂ¤nder ohne Berlin,NaN,12 284,11 173,1 111,1 111,580,375,27,/,/,...,/,18,79,NaN,34,222,107,70,305,NaN
Baden-WĂ¼rttemberg,NaN,10 976,7 154,3 822,3 822,2 613,1 442,37,58,106,...,19,136,174,NaN,516,550,1 461,604,838,NaN
Bayern,NaN,12 920,9 493,3 427,3 427,2 398,1 437,( 33),41,76,...,( 24),104,142,NaN,459,465,1 115,557,880,NaN
Berlin,NaN,3 621,2 369,1 251,1 251,751,356,( 22),26,( 16),...,( 21),30,31,NaN,77,151,374,165,191,NaN
Brandenburg,Brandenburg,2 474,2 246,228,228,130,88,/,/,/,...,/,/,( 13),NaN,/,40,( 20),( 17),71,NaN
Bremen,Bremen,674,418,256,256,137,60,( 9),/,/,...,/,( 6),8,NaN,14,36,72,17,43,NaN
Hamburg,Hamburg,1 828,1 199,630,630,347,168,/,/,/,...,/,( 17),20,NaN,44,66,184,66,102,NaN
Hessen,Hessen,6 201,3 980,2 221,2 221,1 348,696,40,19,39,...,18,73,97,NaN,213,294,820,271,424,NaN
Mecklenburg-Vorpommern,Mecklenburg-Vorpommern,1 581,1 443,138,138,77,49,/,/,/,...,/,/,11,NaN,/,35,( 10),( 11),38,NaN
Nieder-sachsen,Niedersachsen,7 857,6 066,1 791,1 791,1 064,562,( 19),( 10),28,...,25,70,84,NaN,95,386,398,212,350,NaN
Nordrhein-Westfalen,Nordrhein-Westfalen,17 658,12 137,5 521,5 521,3 433,1 757,54,40,152,...,42,179,319,NaN,369,784,1 891,731,1 026,NaN
Rheinland-Pfalz,Rheinland-Pfalz,4 017,2 905,1 112,1 112,686,369,18,21,18,...,( 7),40,43,NaN,93,234,293,147,222,NaN
Saarland,Saarland,968,749,219,219,137,84,/,( 11),/,...,/,/,/,NaN,/,34,65,54,30,NaN
Sachsen,Sachsen,3 995,3 622,373,373,188,117,/,/,/,...,/,( 7),29,NaN,( 11),82,41,25,91,NaN
Sachsen-Anhalt,Sachsen-Anhalt,2 144,1 949,194,194,92,58,/,/,/,...,/,/,17,NaN,/,32,( 21),/,49,NaN
Schleswig-Holstein,Schleswig-Holstein,2 857,2 335,523,523,306,171,/,/,/,...,/,( 15),22,NaN,31,78,125,71,100,NaN
ThĂ¼ringen,ThĂ¼ringen,2 090,1 912,177,177,93,63,/,/,/,...,/,/,( 10),NaN,/,34,16,/,55,NaN
Unnamed: 20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN